# Machine Learning: Assignment 5 
## SVM plus Other Classification Method (max. 10p)

The dataset for the exercise is "Date Fruit Datasets" file you can find from [Date_Fruit_Datasets.xlsx](data/Date_Fruit_Datasets.xlsx), which contains 898 rows and 34 columns of data about dates and a column telling the species of dates. 

There are **seven** (**7**) date fruit species in the dataset, so this is kind of **multi-class classification problem**.

More information about the data and related research: [https://www.muratkoklu.com/datasets/](https://www.muratkoklu.com/datasets/).


In [22]:
# Write Your information in here
student_name = "Kristian Pekkanen, Joonas Lahti"
student_id = "AD0462, AC6855"

## Assignment 5.1
### Topic: Data Preprocessing (2 points)
The dataset has a class variable (*target*) in the last column.

Let's do the following preprocessing steps with the dataset:

1. Load the data into the `DataFrame`.
2. Name the columns of the `DataFrame` according to the material.
3. Preprocess the material
   * Optimize the data input to the machine learning model
   * You can remove "unnecessary features" at your discretion
   * Handling of abnormal (outliers) or empty data values
   * Remember that all categories should be numeric
4. Scale column values by normalizing them.

In [23]:
# TODO: Write your code in this cell

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

df = pd.DataFrame()

df = pd.read_excel("./data/Date_Fruit_Datasets.xlsx", sheet_name="Date_Fruit_Datasets") 

columns = [
    "AREA",
    "PERIMETER",
    "MAJOR_AXIS",
    "MINOR_AXIS",
    "ECCENTRICITY",
    "EQDIASQ",
    "SOLIDITY",
    "CONVEX_AREA",
    "EXTENT",
    "ASPECT_RATIO",
    "ROUNDNESS",
    "COMPACTNESS",
    "SHAPEFACTOR_1",
    "SHAPEFACTOR_2",
    "SHAPEFACTOR_3",
    "SHAPEFACTOR_4",
    "MeanRR",
    "MeanRG",
    "MeanRB",
    "StdDevRR",
    "StdDevRG",
    "StdDevRB",
    "SkewRR",
    "SkewRG",
    "SkewRB",
    "KurtosisRR",
    "KurtosisRG",
    "KurtosisRB",
    "EntropyRR",
    "EntropyRG",
    "EntropyRB",
    "ALLdaub4RR",
    "ALLdaub4RG",
    "ALLdaub4RB",
    "Class",
]

df.columns = columns

In [24]:
# TODO: Plotting features

#Dropping unnecessary columns from the dataset.
df = df.drop(["MeanRR", "MeanRG", "MeanRB", "StdDevRR", "StdDevRG", "StdDevRB", "SkewRR", "SkewRG", "SkewRB", "KurtosisRR", "KurtosisRG", "KurtosisRB", "EntropyRR", "EntropyRG", "EntropyRB", "ALLdaub4RR", "ALLdaub4RG", "ALLdaub4RB"], axis=1)
df = df.drop(["Class"], axis=1)

#Ouliers or empty data values
df = df.apply(lambda x: x.str.reålace(',', '.', regex=False) if x.dtype == 0 else x)

#Converting the data to float 
scaler = StandardScaler()
df = pd.DataFrame(scaler.fit_transform(df), columns=df.columns)

In [25]:
# Answers to the assignment. Note! Do not edit this cell, just run it after you complete the task.
# The DataFrame should be in the df variable.
print(f'Columns: {df.columns}')
print(f'First row by position: {df.iloc[0]}')

Columns: Index(['AREA', 'PERIMETER', 'MAJOR_AXIS', 'MINOR_AXIS', 'ECCENTRICITY',
       'EQDIASQ', 'SOLIDITY', 'CONVEX_AREA', 'EXTENT', 'ASPECT_RATIO',
       'ROUNDNESS', 'COMPACTNESS', 'SHAPEFACTOR_1', 'SHAPEFACTOR_2',
       'SHAPEFACTOR_3', 'SHAPEFACTOR_4'],
      dtype='object')
First row by position: AREA             1.155640
PERIMETER        0.783942
MAJOR_AXIS       0.604507
MINOR_AXIS       1.311643
ECCENTRICITY    -1.129568
EQDIASQ          1.075704
SOLIDITY         0.708628
CONVEX_AREA      1.108752
EXTENT           0.871873
ASPECT_RATIO    -0.046797
ROUNDNESS        1.125433
COMPACTNESS      1.091228
SHAPEFACTOR_1   -0.069867
SHAPEFACTOR_2   -0.688443
SHAPEFACTOR_3    1.169934
SHAPEFACTOR_4    0.240467
Name: 0, dtype: float64


## Assignment 5.2: Training and Testing Data (2 points)

Split the data into training and testing data using the [train_test_split](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html) function of the `scikit-learn` library.
Put *75%* of the data in training data.

1. Save the training data and its class variable to the variables `X_train`, `y_train`,
2. Save the test data to the variables `X_test`, `y_test`.

If you think there are unnecessary variables in the data, you should remove them at this stage.

Use the number `1550` as the random seed and the size of the test data *25%*.

In [32]:
# TODO: Write your implementation in this cell.

# TODO: Choose the appropriate scaling method
# TODO: Normalize the data
from sklearn.model_selection import train_test_split

df = pd.read_excel("./data/Date_Fruit_Datasets.xlsx", sheet_name="Date_Fruit_Datasets")
X = df.drop(["Class"], axis=1)
y = df["Class"]

# TODO: Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=1550)


In [34]:
# Answers to the assignment. Note! Do not edit this cell, just run it after you complete the task.

df_X_train = pd.DataFrame(X_train, columns=X.columns)

print(len(df))
print(len(X_train))
print(len(X_test))
df_X_train.head()

898
673
225


AREA  PERIMETER  MAJOR_AXIS  MINOR_AXIS  ECCENTRICITY   EQDIASQ  \
686  363778  2324.1609    857.5090    541.6883        0.7752  680.5707   
210  137932  1404.5460    524.6572    335.7947        0.7684  419.0710   
768  297174  2155.9590    779.7753    488.4755        0.7795  615.1208   
520  379703  2327.3159    808.6260    603.5130        0.6656  695.3077   
71   265701  1968.8020    746.8929    454.7724        0.7933  581.6365   

     SOLIDITY  CONVEX_AREA  EXTENT  ASPECT_RATIO  ...  SkewRB  KurtosisRR  \
686    0.9859       368999  0.6962        1.5830  ...  0.5565      4.1236   
210    0.9870       139753  0.7834        1.5624  ... -0.2365      2.6462   
768    0.9716       305852  0.6638        1.5963  ...  0.7421      8.8575   
520    0.9815       386849  0.7885        1.3399  ... -0.4954      3.4431   
71     0.9920       267851  0.7619        1.6423  ...  0.1484      2.2009   

     KurtosisRG  KurtosisRB    EntropyRR    EntropyRG    EntropyRB  \
686      8.9859      4.0427 -11916909568 -12828743680 -16592906240   
210      3.0183      2.6045 -16443756544 -16013483008 -15180389376   
768      7.7524      4.7820  -8952644608  -9902926848 -11451906048   
520      3.6240      3.1232 -67456614400 -60271841280 -51568693248   
71       2.3465      2.5310 -44338049024 -38484541440 -32898990080   

     ALLdaub4RR  ALLdaub4RG  ALLdaub4RB  
686     29.3568     30.2898     34.5888  
210     54.1920     54.1965     52.2736  
768     25.8247     28.4548     32.2477  
520     65.5561     62.4925     57.4187  
71      62.8217     58.8671     55.4206  

[5 rows x 34 columns]

## Task 5.3: Implement Support Vector Machine Classification (2 points)

1. Use the `scikit-learn` library's *Linear Support Vector Classification* function to train a classifier with your training data that classifies each date fruit species.

2. Create predictions for the data points of your test data in the `y_pred` variable.

3. Use the `metrics` module to make a [classification report](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.classification_report.html) for the predictions of your test data. Save results to the `cr` variable.

4. Use the `metrics` module to make a **confusion matrix** and store it in the `cm` variable.

In [35]:
# TODO: Write your implementation in this cell.
# TODO: use LinearSVC.

from sklearn.svm import LinearSVC
from sklearn.metrics import classification_report, confusion_matrix

svm_model = LinearSVC()
svm_model.fit(X_train, y_train)

y_pred = svm_model.predict(X_test)

# Generate classification report
cr = classification_report(y_test, y_pred)

# Generate confusion matrix
cm = confusion_matrix(y_test, y_pred)

c:\Users\Joonas\Desktop\KouluJamk\ml-assignments\.venv\Lib\site-packages\sklearn\svm\_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(
c:\Users\Joonas\Desktop\KouluJamk\ml-assignments\.venv\Lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\Joonas\Desktop\KouluJamk\ml-assignments\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Joonas\Desktop\KouluJamk\ml-assignments\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being se

In [38]:
# Answers to the assignment. Note! Do not edit this cell, just run it after you complete the task.
# The results are in cm and cr variables.
print(f'Classification report:\n {cr}')
print(f'Confusion matrix:\n {cm}')

Classification report:
               precision    recall  f1-score   support

       BERHI       0.00      0.00      0.00        19
      DEGLET       0.00      0.00      0.00        17
       DOKOL       0.00      0.00      0.00        54
       IRAQI       0.12      0.67      0.20        21
      ROTANA       0.00      0.00      0.00        44
      SAFAVI       0.84      0.87      0.85        47
       SOGAY       0.34      0.78      0.47        23

    accuracy                           0.32       225
   macro avg       0.18      0.33      0.22       225
weighted avg       0.22      0.32      0.25       225

Confusion matrix:
 [[ 0  0  0 16  0  1  2]
 [ 1  0  0  6  0  0 10]
 [ 2  0  0 38  0  0 14]
 [ 0  0  0 14  0  7  0]
 [ 1  0  0 35  0  0  8]
 [ 0  0  0  5  0 41  1]
 [ 0  0  0  5  0  0 18]]


## Assignment 5.4: Comparison with another ML method and analysis of the results (2 points)

Verbally interpret the obtained test results.
* How well the support vector did in the classification task

For comparison, try teaching the model using another classification method:
* The method can be **RandomForest** (or if you want **DecisionTree** etc., but still justify your choice)
So you can freely select the ML classification method used in this comparison.

In [39]:
# TODO: Write your implementation in this cell.

# TODO: Implementation of another Machine Learning Classification method.
# TODO: The method can be RandomForest or any other method that works with this data "well enough".

# TODO: Write your implementation in this cell.

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.svm import LinearSVC

svm_model = LinearSVC(random_state=1550)
svm_model.fit(X_train, y_train)
y_pred_svm = svm_model.predict(X_test)

# RandomForest Classifier
rf_model = RandomForestClassifier(random_state=1550)
rf_model.fit(X_train, y_train)
y_pred_rf = rf_model.predict(X_test)

# Evaluate SVM
accuracy_svm = accuracy_score(y_test, y_pred_svm)
report_svm = classification_report(y_test, y_pred_svm)
conf_matrix_svm = confusion_matrix(y_test, y_pred_svm)

# Evaluate RandomForest
accuracy_rf = accuracy_score(y_test, y_pred_rf)
report_rf = classification_report(y_test, y_pred_rf)
conf_matrix_rf = confusion_matrix(y_test, y_pred_rf)

# Interpret the results
print("Support Vector Machine (SVM) Results:")
print(f"Accuracy: {accuracy_svm:.2f}")
print("Classification Report:\n", report_svm)
print("Confusion Matrix:\n", conf_matrix_svm)

print("\nRandomForest Results:")
print(f"Accuracy: {accuracy_rf:.2f}")
print("Classification Report:\n", report_rf)
print("Confusion Matrix:\n", conf_matrix_rf)

c:\Users\Joonas\Desktop\KouluJamk\ml-assignments\.venv\Lib\site-packages\sklearn\svm\_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(
c:\Users\Joonas\Desktop\KouluJamk\ml-assignments\.venv\Lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


Support Vector Machine (SVM) Results:
Accuracy: 0.39
Classification Report:
               precision    recall  f1-score   support

       BERHI       0.00      0.00      0.00        19
      DEGLET       0.00      0.00      0.00        17
       DOKOL       0.31      0.74      0.44        54
       IRAQI       0.00      0.00      0.00        21
      ROTANA       0.00      0.00      0.00        44
      SAFAVI       0.49      0.96      0.65        47
       SOGAY       0.60      0.13      0.21        23

    accuracy                           0.39       225
   macro avg       0.20      0.26      0.19       225
weighted avg       0.24      0.39      0.26       225

Confusion Matrix:
 [[ 0  0  9  0  0 10  0]
 [ 0  0 13  0  0  2  2]
 [ 0  0 40  0  0 14  0]
 [ 0  0  3  0  0 18  0]
 [ 0  0 42  0  0  2  0]
 [ 0  0  2  0  0 45  0]
 [ 0  0 20  0  0  0  3]]

RandomForest Results:
Accuracy: 0.90
Classification Report:
               precision    recall  f1-score   support

       BERHI       0.

c:\Users\Joonas\Desktop\KouluJamk\ml-assignments\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Joonas\Desktop\KouluJamk\ml-assignments\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Joonas\Desktop\KouluJamk\ml-assignments\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average,

## Assignment 5.5: Analysis of the results (2 points)
Let's do comparison of Different Classification Models used in this assignment.
* Compare the classification results of SVM and Selected Classification models.
* Compare the obtained results and interpret the results verbally.
* Compare the **accuracy** and **confusion matrix** of the classification results for both methods.

In [40]:
# TODO: Compare the accuracy of the classification results of both classification methods.
# TODO: Compare the confusion matrix of both classification methods with each other.

# SVM Results
print("Support Vector Machine (SVM) Results:")
print(f"Accuracy: {accuracy_svm:.2f}")
print("Confusion Matrix:\n", conf_matrix_svm)

# RandomForest Results
print("\nRandomForest Results:")
print(f"Accuracy: {accuracy_rf:.2f}")
print("Confusion Matrix:\n", conf_matrix_rf)

Support Vector Machine (SVM) Results:
Accuracy: 0.39
Confusion Matrix:
 [[ 0  0  9  0  0 10  0]
 [ 0  0 13  0  0  2  2]
 [ 0  0 40  0  0 14  0]
 [ 0  0  3  0  0 18  0]
 [ 0  0 42  0  0  2  0]
 [ 0  0  2  0  0 45  0]
 [ 0  0 20  0  0  0  3]]

RandomForest Results:
Accuracy: 0.90
Confusion Matrix:
 [[15  0  0  4  0  0  0]
 [ 0 11  3  0  0  0  3]
 [ 0  5 49  0  0  0  0]
 [ 1  0  0 20  0  0  0]
 [ 0  1  0  0 42  0  1]
 [ 0  0  0  0  0 47  0]
 [ 0  4  0  0  1  0 18]]


Q: Are there other good classification methods to apply with this dataset or any other way to improve the classification results?